"""initial schema with shortuuid

Revision ID: 0dd988c6b130
Revises: 
Create Date: 2026-06-03 00:05:39.123558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0dd988c6b130'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spots',
    sa.Column('uid', sa.String(length=22), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('address_detail', sa.String(), nullable=True),
    sa.Column('region_province', sa.String(), nullable=True),
    sa.Column('region_city', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('tagline', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('unit_count', sa.Integer(), nullable=True),
    sa.Column('is_fee_required', sa.Boolean(), nullable=True),
    sa.Column('is_pet_allowed', sa.Boolean(), nullable=True),
    sa.Column('pet_policy', sa.String(), nullable=True),
    sa.Column('has_equipment_rental', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('themes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('fire_pit_type', sa.String(), nullable=True),
    sa.Column('amenities', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('nearby_facilities', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('camp_sight_type', sa.String(), nullable=True),
    sa.Column('rating_avg', sa.Float(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('booking_url', sa.String(), nullable=True),
    sa.Column('features', sa.String(), nullable=True),
    sa.Column('category', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('total_area_m2', sa.Float(), nullable=True),
    sa.Column('has_liability_insurance', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('source', 'external_id', name='uq_spots_source_external_id')
    )
    op.create_index(op.f('ix_spots_rating_avg'), 'spots', ['rating_avg'], unique=False)
    op.create_index(op.f('ix_spots_region_city'), 'spots', ['region_city'], unique=False)
    op.create_index(op.f('ix_spots_region_province'), 'spots', ['region_province'], unique=False)
    op.create_index(op.f('ix_spots_source'), 'spots', ['source'], unique=False)
    op.create_index(op.f('ix_spots_title'), 'spots', ['title'], unique=False)
    op.create_table('users',
    sa.Column('uid', sa.String(length=22), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('google_sub', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('picture', sa.String(length=2048), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('membership_tier', sa.Enum('free', 'member', name='membership_tier'), server_default='free', nullable=False),
    sa.Column('identity_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onboarding_survey_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=True)
    op.create_table('jobs',
    sa.Column('uid', sa.String(length=22), nullable=False),
    sa.Column('type', sa.Enum('spots_bulk_upsert', 'spot_business_info_bulk_upsert', name='job_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', name='job_status'), server_default='pending', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=22), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('spot_business_info',
    sa.Column('uid', sa.String(length=22), nullable=False),
    sa.Column('spot_uid', sa.String(length=22), nullable=False),
    sa.Column('business_reg_no', sa.String(), nullable=True),
    sa.Column('tourism_business_reg_no', sa.String(), nullable=True),
    sa.Column('business_type', sa.String(), nullable=True),
    sa.Column('operation_type', sa.String(), nullable=True),
    sa.Column('operating_agency', sa.String(), nullable=True),
    sa.Column('operating_status', sa.String(), nullable=True),
    sa.Column('national_park_no', sa.Integer(), nullable=True),
    sa.Column('national_park_office_code', sa.String(), nullable=True),
    sa.Column('national_park_serial_no', sa.String(), nullable=True),
    sa.Column('national_park_category_code', sa.String(), nullable=True),
    sa.Column('licensed_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['spot_uid'], ['spots.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_spot_business_info_operating_status'), 'spot_business_info', ['operating_status'], unique=False)
    op.create_index(op.f('ix_spot_business_info_spot_uid'), 'spot_business_info', ['spot_uid'], unique=False)
    op.create_table('spot_reviews',
    sa.Column('uid', sa.String(length=22), nullable=False),
    sa.Column('spot_uid', sa.String(length=22), nullable=False),
    sa.Column('user_id', sa.String(length=22), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('rating >= 0 AND rating <= 5', name='check_review_rating_range'),
    sa.ForeignKeyConstraint(['spot_uid'], ['spots.uid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('spot_uid', 'user_id', name='uq_spot_user_review')
    )
    op.create_index(op.f('ix_spot_reviews_spot_uid'), 'spot_reviews', ['spot_uid'], unique=False)
    op.create_index(op.f('ix_spot_reviews_user_id'), 'spot_reviews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spot_reviews_user_id'), table_name='spot_reviews')
    op.drop_index(op.f('ix_spot_reviews_spot_uid'), table_name='spot_reviews')
    op.drop_table('spot_reviews')
    op.drop_index(op.f('ix_spot_business_info_spot_uid'), table_name='spot_business_info')
    op.drop_index(op.f('ix_spot_business_info_operating_status'), table_name='spot_business_info')
    op.drop_table('spot_business_info')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_spots_title'), table_name='spots')
    op.drop_index(op.f('ix_spots_source'), table_name='spots')
    op.drop_index(op.f('ix_spots_region_province'), table_name='spots')
    op.drop_index(op.f('ix_spots_region_city'), table_name='spots')
    op.drop_index(op.f('ix_spots_rating_avg'), table_name='spots')
    op.drop_table('spots')
    # ### end Alembic commands ###
