"""add dm conversations messages user_blocks tables

Revision ID: 58f418a45d9a
Revises: a7c3e1f9b204
Create Date: 2026-08-22 14:57:08.122409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58f418a45d9a'
down_revision: Union[str, None] = 'a7c3e1f9b204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('uid', sa.String(length=22), nullable=False),
    sa.Column('type', sa.Enum('direct', 'group', name='conversation_type'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("uid ~ '^[0-9A-Za-z]{22}$'", name='ck_conversations_uid_format'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('conversation_participants',
    sa.Column('conversation_uid', sa.String(length=22), nullable=False),
    sa.Column('user_uid', sa.String(length=22), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_uid'], ['conversations.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('conversation_uid', 'user_uid')
    )
    op.create_index(op.f('ix_conversation_participants_user_uid'), 'conversation_participants', ['user_uid'], unique=False)
    op.create_table('messages',
    sa.Column('uid', sa.String(length=22), nullable=False),
    sa.Column('conversation_uid', sa.String(length=22), nullable=False),
    sa.Column('sender_uid', sa.String(length=22), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("uid ~ '^[0-9A-Za-z]{22}$'", name='ck_messages_uid_format'),
    sa.ForeignKeyConstraint(['conversation_uid'], ['conversations.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_messages_conversation_uid'), 'messages', ['conversation_uid'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_table('user_blocks',
    sa.Column('blocker_uid', sa.String(length=22), nullable=False),
    sa.Column('blocked_uid', sa.String(length=22), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('blocker_uid <> blocked_uid', name='ck_user_blocks_no_self_block'),
    sa.ForeignKeyConstraint(['blocked_uid'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['blocker_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('blocker_uid', 'blocked_uid')
    )
    op.create_index(op.f('ix_user_blocks_blocked_uid'), 'user_blocks', ['blocked_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_blocks_blocked_uid'), table_name='user_blocks')
    op.drop_table('user_blocks')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_uid'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversation_participants_user_uid'), table_name='conversation_participants')
    op.drop_table('conversation_participants')
    op.drop_table('conversations')
    # ### end Alembic commands ###
    sa.Enum(name='conversation_type').drop(op.get_bind())
