"""add source and external_id to spots

Revision ID: 62795cd8d6c0
Revises: 1c2f1b92a707
Create Date: 2026-05-21 02:01:56.189522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62795cd8d6c0'
down_revision: Union[str, None] = '1c2f1b92a707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spots', sa.Column('source', sa.String(), nullable=True))
    op.add_column('spots', sa.Column('external_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_spots_source'), 'spots', ['source'], unique=False)
    op.create_unique_constraint('uq_spots_source_external_id', 'spots', ['source', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_spots_source_external_id', 'spots', type_='unique')
    op.drop_index(op.f('ix_spots_source'), table_name='spots')
    op.drop_column('spots', 'external_id')
    op.drop_column('spots', 'source')
    # ### end Alembic commands ###
